# @package _global_

agent:
  name: softq
  class: agent.softq.SoftQ
  obs_dim: ??? # to be specified later
  action_dim: ??? # to be specified later

  critic_cfg: ${q_net}
  reward_cfg: ${r_net}
  critic_lr: 5e-3 #1e-4 # 5e-3  for CartPole and Acrobot
  critic_betas: [0.9, 0.999] #[0.9, 0.999]

  init_temperature: 0.01
  critic_target_update_frequency: 4
  critic_tau: 0.1

q_net:
  _target_: agent.softq_models.SimpleQNetwork
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}

r_net:
  _target_: agent.softq_models.SimpleRNetwork
  obs_dim: ${agent.obs_dim}
  action_dim: ${agent.action_dim}